Badge
raghav6202/Jatayu-UI-Component-Library pull request #4
Opened 2022-02-04 14:52 UTC by raghav6202

Please review the badge component
U.I snippet attached below

<img width="940" alt="image" src="https://user-images.githubusercontent.com/86127392/152549703-3fbbe22b-4293-4b54-8c63-44280713004c.png">

2022-02-16 14:54 UTC, rishbitsnbytes reviewed
Comment usage is required. Other comments are mentioned, rest looks good.

2022-02-16 14:54 UTC, rishbitsnbytes commented on Components/badges/badges.css
> +
remove spacing.

2022-02-16 14:54 UTC, rishbitsnbytes commented on Components/badges/badges.css
> +.badge .img-badge ~ .status-indicator{
also keep consistency in braces placement, improve formatting.

2022-02-16 14:54 UTC, rishbitsnbytes commented on Components/badges/badges.css
> +
same spacing.

2022-02-16 14:54 UTC, rishbitsnbytes commented on Components/badges/badges.html
> +
use prettier to beautify code

2022-02-16 16:08 UTC, ravikumar0403 requested changes
Added a few comments. Another suggestion is to use some extensions to format the code. You can try out prettier.

2022-02-16 16:08 UTC, ravikumar0403 commented on Components/badges/badges.css
> +    background-color: red;
use variables for colors

2022-02-16 16:08 UTC, ravikumar0403 commented on Components/badges/badges.css
> +    /* border: 2px solid white; */
remove commented code if not required

2022-02-16 16:08 UTC, ravikumar0403 commented on Components/badges/badges.html
> +    <title>Document</title>
Change this title to be relevant with your page

2022-02-16 16:08 UTC, ravikumar0403 commented on Components/badges/styles.css
> +}
Don't declare variable colors in every other css file. Instead, create a separate file for all the variables. This will help in the maintainability

2022-02-16 16:08 UTC, ravikumar0403 commented on Components/badges/styles.css
> +}
remove commented code if not required

2022-02-16 16:08 UTC, ravikumar0403 commented on Components/badges/styles.css
> +    margin: 0.2rem;
Not mandatory but if the value is less than 10px then you can avoid using rems

2022-02-16 16:08 UTC, ravikumar0403 commented on Components/badges/styles.css
> +    background-color: white;
You should use variables even for these colors, This will help in the future when you just want to change the color then you won't have to search through the entire file

2022-02-16 16:08 UTC, ravikumar0403 commented on Components/badges/styles.css
> +    background-color: #FAFAFA;
here as well. use variables

2022-02-17 04:24 UTC, raghav6202 commented on Components/badges/styles.css
> +    background-color: #FAFAFA;
Thank you Ravi will look into the changes

2022-02-17 04:25 UTC, raghav6202 commented on Components/badges/badges.html
> +
done! Thank you for your suggestions.

2022-02-17 04:25 UTC, merged